// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXN0yk02hE5xHtHFQr3YOayME232YDHEE',
    appId: '1:436372321001:web:00fd371586b1e47b25b678',
    messagingSenderId: '436372321001',
    projectId: 'storageintdb',
    authDomain: 'storageintdb.firebaseapp.com',
    storageBucket: 'storageintdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA64fs7-UjCzSbk5Py7ZuRIynwkJTNZ4og',
    appId: '1:436372321001:android:ae8af58e382ebffc25b678',
    messagingSenderId: '436372321001',
    projectId: 'storageintdb',
    storageBucket: 'storageintdb.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ffXU_kzdFY4QXj2lZcVFpmcqOhrorXs',
    appId: '1:436372321001:ios:a061d0e4b0faed1a25b678',
    messagingSenderId: '436372321001',
    projectId: 'storageintdb',
    storageBucket: 'storageintdb.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ffXU_kzdFY4QXj2lZcVFpmcqOhrorXs',
    appId: '1:436372321001:ios:a061d0e4b0faed1a25b678',
    messagingSenderId: '436372321001',
    projectId: 'storageintdb',
    storageBucket: 'storageintdb.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXN0yk02hE5xHtHFQr3YOayME232YDHEE',
    appId: '1:436372321001:web:4aab62110592f7b725b678',
    messagingSenderId: '436372321001',
    projectId: 'storageintdb',
    authDomain: 'storageintdb.firebaseapp.com',
    storageBucket: 'storageintdb.appspot.com',
  );

}